<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8c3828a5-7c4e-400c-a2e3-f0b11ddb16da</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	<None Update="componentConfig.json">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
	<None Update="bot_refresh_token.txt">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="TwitchLib.Api" Version="3.10.2" />
    <PackageReference Include="TwitchLib.Client" Version="4.0.1" />
  </ItemGroup>

</Project>
